allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
glintBrightness=110
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.8.1 + EuphoriaPatches_1.9.3
tintBrightness=75
wynncraftEntityBrightness=100
wynncraftEntityEmissivity=100
wynncraftMistWoodsFog=true
wynncraftMistWoodsFogDensity=100
wynncraftMistWoodsFogMinDistance=0
wynncraftMistWoodsFogSunTintAmount=50
wynncraftMistWoodsFogSunTintReduction=false
wynncraftMountArmorOverlay=false
wynncraftNightVisionDisablesBoost=true
wynncraftSceneDarkening=100
wynncraftTextBrightnessFloor=false
wynncraftTextBrightnessFloorLevel=10
