name = "Wynncraft"
author = "ShaksterNano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a372fd7bcb20933daeefb705c997fe92e56aa788ff46f71dedcf0021c947c3e"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
