name = "Wynncraft"
author = "ShaksterNano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc7c2105265eda5334c14c06ab932fb4381cc0d671eb89e3162a90cd0474801f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
