name = "Vanilla"
author = "ShaksterNano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd397b7a07f5cd920e7b56058e3839f762eac1fb5ebb9acc700ce987b56da4a7"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
