name = "Vanilla"
author = "ShaksterNano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b2281ce745b5f97c7a6b4f9329d016f7c21f40bbb691ef562640bc5e41c321c"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
