name = "Vanilla"
author = "ShaksterNano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd05a5c3e4b81446b8dc552efcdf0f686bf94dee24b19f2b4037b3e27c0d23f2"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
