name = "Kaikai SMP"
author = "ShaksterNano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "757b71c1ff8922bd880eb51e97d6a29e27743f30baa74c5233de10e3e10058af"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
