name = "Kaikai SMP"
author = "ShaksterNano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bb08e5ab632530f7e3a5dd25f276c7038d0b01b47ee2124c7ec19208aab1b51"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
