name = "Kaikai SMP"
author = "ShaksterNano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "329c03e419f44b29ce529b5a0fdf3bf9b9721cf162aae54438b5b3c7f478edca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
