name = "Kaikai SMP"
author = "ShaksterNano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9682f3f8c12a229b7800539b61c6f90644f5ac2ed2dbf389240f2250fcc38638"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"
