name = "Kaikai SMP"
author = "ShaksterNano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63555bb0c95b433b518dde69f0005ce99f2ac1ab581b57a7ddee27a17b337cb2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
