name = "Kaikai SMP"
author = "ShaksterNano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f033d484f45174c6a63c4b7cb2bc418bbeacdc0eca5a9df5aa48d13874e1fcbb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"
